CREATE TABLE IF NOT EXISTS SHEDLOCK (
(
    name       VARCHAR(64)  NOT NULL COMMENT '이름',
    lock_until TIMESTAMP(3) NOT NULL COMMENT '잠금 기간',
    locked_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '잠금 일시',
    locked_by  VARCHAR(255) NOT NULL COMMENT '잠금 실행자',
    PRIMARY KEY (name)
) COMMENT 'SHEDLOCK TABLE';

CREATE TABLE IF NOT EXISTS TASK_RUN_HIST (
    RUN_TMSTP   TIMESTAMP,
    NAME        VARCHAR2(50),
    TYPE        VARCHAR(30),
    DESCRIPTION VARCHAR2(200)
) COMMENT 'SHEDLOCK SCHEDULER 테스트용 테이블';